// Generate dist/css/index.css from the SAME token source the JS bundle ships, so
// the web CSS variables can never drift from the TS tokens. Run AFTER tsup (it
// imports the freshly built dist/index.js). Emits two blocks:
//   :root, [data-theme="light"] { … }   ← themeToCSSVars(themes.light)
//   [data-theme="dark"]        { … }   ← themeToCSSVars(themes.dark)
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { themes, themeToCSSVars } from "../dist/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const cssDir = join(here, "..", "dist", "css");

const block = (selector, vars) => {
  const body = Object.entries(vars)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
  return `${selector} {\n${body}\n}`;
};

const css =
  [
    "/* AUTO-GENERATED by scripts/build-css.mjs from src/tokens.ts — do not edit by hand. */",
    block(':root,\n[data-theme="light"]', themeToCSSVars(themes.light)),
    block('[data-theme="dark"]', themeToCSSVars(themes.dark)),
  ].join("\n\n") + "\n";

mkdirSync(cssDir, { recursive: true });
writeFileSync(join(cssDir, "index.css"), css, "utf8");
console.log(`build-css: wrote ${join("dist", "css", "index.css")}`);
